\c authuser

INSERT INTO permissions (code) VALUES 
    ('MODIFY_USER'),
    ('READ_USER'),
    ('DELETE_USER'),
    ('CREATE_ROLE'),
    ('MODIFY_ROLE'),
    ('READ_ROLE'),
    ('DELETE_ROLE'),
    ('CREATE_PERMISSION'),
    ('MODIFY_PERMISSION'),
    ('READ_PERMISSION'),
    ('DELETE_PERMISSION'),
    ('CREATE_PERSON'),
    ('MODIFY_PERSON'),
    ('READ_PERSON'),
    ('DELETE_PERSON'),
    ('CREATE_CITY'),
    ('MODIFY_CITY'),
    ('READ_CITY'),
    ('DELETE_CITY'),
    ('CREATE_PROVINCE'),
    ('MODIFY_PROVINCE'),
    ('READ_PROVINCE'),
    ('DELETE_PROVINCE'),
    ('CREATE_COUNTRY'),
    ('MODIFY_COUNTRY'),
    ('READ_COUNTRY'),
    ('DELETE_COUNTRY');

INSERT INTO roles (name) VALUES 
    ('Guest'),
    ('User'),
    ('Moderator'),
    ('Admin');


INSERT INTO roles_permissions ("rolesId", "permissionsId") VALUES 
    (2,2),
    (3,1),
    (3,2),
    (3,3),
    (3,4),
    (3,5),
    (3,6),
    (3,7),
    (3,8),
    (3,9),
    (3,10),
    (3,11),
    (4,1),
    (4,2),
    (4,3),
    (4,4),
    (4,5),
    (4,6),
    (4,7),
    (4,8),
    (4,9),
    (4,10),
    (4,11),
    (4,12),
    (4,13),
    (4,14),
    (4,15),
    (4,16),
    (4,17),
    (4,18),
    (4,19),
    (4,20),
    (4,21),
    (4,22),
    (4,23),
    (4,24),
    (4,25),
    (4,26);

INSERT INTO users (name, email, password, "rolesId") VALUES
    ('Marquito', 'marquito@gmail.com', '1234567', 1),
    ('Jorgelito', 'jorgelito@gmail.com', '1234567', 3),
    ('Juansito', 'juansito@gmail.com', '1234567', 4);